package models;
// Generated 3 dic. 2019 20:13:33 by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;

/**
 * TEstaciones generated by hbm2java
 */
public class TEstaciones implements java.io.Serializable {

	private int codEstacion;
	private String nombre;
	private String direccion;
	private Integer numaccesos;
	private Integer numlineas;
	private Integer numviajesdestino;
	private Integer numviajesprocedencia;
	private Set<TViajes> TViajesesForEstacionorigen = new HashSet<TViajes>(0);
	private Set<TViajes> TViajesesForEstaciondestino = new HashSet<TViajes>(0);
	private Set<TLineaEstacion> TLineaEstacions = new HashSet<TLineaEstacion>(0);
	private Set<TAccesos> TAccesoses = new HashSet<TAccesos>(0);

	public TEstaciones() {
	}

	public TEstaciones(int codEstacion, String nombre, String direccion) {
		this.codEstacion = codEstacion;
		this.nombre = nombre;
		this.direccion = direccion;
	}

	public TEstaciones(int codEstacion, String nombre, String direccion, Integer numaccesos, Integer numlineas,
			Integer numviajesdestino, Integer numviajesprocedencia, Set<TViajes> TViajesesForEstacionorigen,
			Set<TViajes> TViajesesForEstaciondestino, Set<TLineaEstacion> TLineaEstacions, Set<TAccesos> TAccesoses) {
		this.codEstacion = codEstacion;
		this.nombre = nombre;
		this.direccion = direccion;
		this.numaccesos = numaccesos;
		this.numlineas = numlineas;
		this.numviajesdestino = numviajesdestino;
		this.numviajesprocedencia = numviajesprocedencia;
		this.TViajesesForEstacionorigen = TViajesesForEstacionorigen;
		this.TViajesesForEstaciondestino = TViajesesForEstaciondestino;
		this.TLineaEstacions = TLineaEstacions;
		this.TAccesoses = TAccesoses;
	}

	public int getCodEstacion() {
		return this.codEstacion;
	}

	public void setCodEstacion(int codEstacion) {
		this.codEstacion = codEstacion;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	public Integer getNumaccesos() {
		return this.numaccesos;
	}

	public void setNumaccesos(Integer numaccesos) {
		this.numaccesos = numaccesos;
	}

	public Integer getNumlineas() {
		return this.numlineas;
	}

	public void setNumlineas(Integer numlineas) {
		this.numlineas = numlineas;
	}

	public Integer getNumviajesdestino() {
		return this.numviajesdestino;
	}

	public void setNumviajesdestino(Integer numviajesdestino) {
		this.numviajesdestino = numviajesdestino;
	}

	public Integer getNumviajesprocedencia() {
		return this.numviajesprocedencia;
	}

	public void setNumviajesprocedencia(Integer numviajesprocedencia) {
		this.numviajesprocedencia = numviajesprocedencia;
	}

	public Set<TViajes> getTViajesesForEstacionorigen() {
		return this.TViajesesForEstacionorigen;
	}

	public void setTViajesesForEstacionorigen(Set<TViajes> TViajesesForEstacionorigen) {
		this.TViajesesForEstacionorigen = TViajesesForEstacionorigen;
	}

	public Set<TViajes> getTViajesesForEstaciondestino() {
		return this.TViajesesForEstaciondestino;
	}

	public void setTViajesesForEstaciondestino(Set<TViajes> TViajesesForEstaciondestino) {
		this.TViajesesForEstaciondestino = TViajesesForEstaciondestino;
	}

	public Set<TLineaEstacion> getTLineaEstacions() {
		return this.TLineaEstacions;
	}

	public void setTLineaEstacions(Set<TLineaEstacion> TLineaEstacions) {
		this.TLineaEstacions = TLineaEstacions;
	}

	public Set<TAccesos> getTAccesoses() {
		return this.TAccesoses;
	}

	public void setTAccesoses(Set<TAccesos> TAccesoses) {
		this.TAccesoses = TAccesoses;
	}

}
